### ISSUE TITLE
s

### ISSUE THREAD

**Issue by printlybyte** [zhongjihao/android_librtmp_project#1]
05-11 16:46:02.451 31717-31717/com.android.rtmpvideo E/Zygote: v2
05-11 16:46:02.451 31717-31717/com.android.rtmpvideo E/Zygote: accessInfo : 0
05-11 16:46:07.431 31717-31731/com.android.rtmpvideo E/RTMP-JNI: Java_com_android_rtmpvideo_RtmpJni_initRtmp: ======zhongjihao=====open: No such file or directory
05-11 16:46:07.431 31717-31731/com.android.rtmpvideo A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1000e5 in tid 31731 (publish-thread)

**Comment by zhongjihao** [comment]
这个文件路径是在MainActivity.java文件中获取的
 String logPath = Environment.getExternalStorageDirectory() + "/" + "zhongjihao/rtmp.log";
 mediaPublisher = MediaPublisher.newInstance(rtmpUrl,logPath);

请在JNIEXPORT jlong JNICALL Java_com_android_rtmpvideo_RtmpJni_initRtmp(JNIEnv* env,jclass jcls,jstring jurl,jstring jlogpath)
{
    ALOGD("%s: E: ====zhongjihao====Rtmp NetConnect======",__FUNCTION__);
    int ret = 0;
    const char* url = env->GetStringUTFChars(jurl,NULL);
    const char* logpath = env->GetStringUTFChars(jlogpath,NULL);
    CRtmpWrap* pRtmpH264 = new CRtmpWrap;
    pLogfile = fopen(logpath,"w+");
    if(!pLogfile) {
        ALOGE("%s: ======zhongjihao=====open: %s",__FUNCTION__,strerror(errno));
        goto failed;
    }

你应该在你手机存储目录下创建zhongjihao目录 即可
String logPath = Environment.getExternalStorageDirectory() + "/" + "zhongjihao/rtmp.log";

**Comment by zhongjihao** [comment]
录像分屏现象已经解决，请更新最新代码
